sudo: true
git:
  depth: 1

matrix:
  include:
    - name: "Ant Mac IOS Build"
      language: java
      jdk: 
        - openjdk8
      os: osx
      before_install:
        - brew update
        - brew install ant
      install:
        - true
      script:
        - ant -f build-mac-ios.xml
        - mvn clean compile assembly:single

before_deploy:
    - mkdir MiningBuild
    - find . -name '*.jar' -exec cp {} ./MiningBuild \;
    - cd /home/travis/build/build-test-conflicts/canal/MiningBuild
    - tar -zcvf result.tar.gz *
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: result.tar.gz
  name: fetchjar-adccc0e9
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    all_branches: true 
